ALL_WIN = ''
ALL_MAC = ''
ALL_LINUX = ''
log_path_distribute = '/Library/tron/log/distribute_log/'
log_path_server = '/Library/tron/log/server_log/'
log_path_callback = '/Library/tron/log/callback_log/'
outputpath = '/Tron/%s/Vender/outgoing/%s'
# log_path = '/Public/tronPipelineScript/tron2.0/log/'
