"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import glob
import os
from setuptools import setup

def find_data_files(source,target,patterns):

    ret = {}
    for pattern in patterns:
        pattern = os.path.join(source,pattern)
        for filename in glob.glob(pattern):
            if os.path.isfile(filename):
                targetpath = os.path.join(target,os.path.relpath(filename,source))
                path = os.path.dirname(targetpath)
                ret.setdefault(path,[]).append(filename)
    return sorted(ret.items())

APP = [{'script':'IlluminaConverter_v002.py'}]

OPTIONS = {
            'argv_emulation': True,
            'includes':['sip',],
            'dll_excludes':['MSVC90.dll',]
           }

setup(
    app=APP,
    data_files=find_data_files('','',['icon/*','doc/design/*','config/*']),
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
